### ISSUE TITLE
./build.sh: line 10: 56666 Illegal instruction: 4  ./lite_rvm

### ISSUE THREAD

**Issue by Tang-Hai** [DefTruth/RobustVideoMatting.lite.ai.toolkit#11]
我想把 lite.ai.toolkit 打包成一个库，在我的 mac app 中使用，我 git 下来项目后执行 sh ./build.sh 报错，./build.sh: line 10: 56666 Illegal instruction: 4  ./lite_rvm,   我的最终目的是想把 lite.ai.toolkit 打包成一个库，能直接放到我的 xcode 项目中使用，我对 CMakeLists 不熟悉，还是得请教一下您，怎么实现我的最终目标。

**Comment by DefTruth** [comment]
编译lite.ai.toolkit，需要用到cmake，你需要先安装cmake:
```shell
brew install cmake
```
 Illegal instruction: 4，这个问题我也没遇到过。你可参考一下以下的链接：
* https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10
* https://zhuanlan.zhihu.com/p/398121154
CMakeLists语法是比较复杂，但基础的用法也比较简单，建议你可看一下相关的资料，我这里很难展开讲。可以参考下：
* https://zhuanlan.zhihu.com/p/449779892
另外就是，你可以考虑单独从lite.ai.toolkit中抠出RobustVideoMatting的源码来自己用，或者参考这里的源码自己写一份实现就可以了，模型可以从README.md中下载，也不会太复杂。
* https://github.com/DefTruth/lite.ai.toolkit/blob/main/lite/ort/cv/rvm.cpp
