### ISSUE TITLE
Macos下编译失败

### ISSUE THREAD

**Issue by Richardlyq** [DefTruth/RobustVideoMatting.lite.ai.toolkit#30]
作者，您好，查看了一下，上面都是一样的，但是下面多出了很多东西。
<img width="887" alt="Macos下编译出错" src="https://user-images.githubusercontent.com/78252642/158833779-e9d3793b-5767-4821-ac1d-392a6aefa251.png">
还有，您说的把ffmpeg的库和opencv的库放在一起，是将ffmpeg下的lib文件放在RobustVideoMatting.lite.ai.toolkit\lite.ai.toolkit\lib里面嘛？在macos也要这样嘛？macos下我看您就写了两行代码呀，一行是git clone,一行是sh ./build.sh呀，还需要其他什么操作呀？（小白，望大佬多包含，~ ~）

**Comment by DefTruth** [comment]
你用最新的代码就可以了。需要把库和可执行文件放在一起，在examples/build，不是lib。因为我编的ffmpeg是 `./` 的安装路径，表示当前目录，不是 `@rpath`. 具体逻辑可以看一下我写的文章： 

*  [🤓opencv+ffmpeg编译打包全解指南](https://zhuanlan.zhihu.com/p/472115312)
