### ISSUE TITLE
请问用官方的export导出为fp16的onnx时，为何输入是fp16，输出依旧是fp32？

### ISSUE THREAD

**Issue by cvDFT** [DefTruth/RobustVideoMatting.lite.ai.toolkit#32]
![image](https://user-images.githubusercontent.com/94675255/159162958-5027cb00-9e37-4561-9312-2bd834df0896.png)

**Comment by DefTruth** [comment]
这个确实没有研究过，官方的fp16应该是RVM的原作者导出的，我自己还没有尝试过导出fp16

**Comment by cvDFT** [comment]
谢谢你的回复，我再研究一下
