### ISSUE TITLE
windows下编译失败（lite.tool.kit已编译好）

### ISSUE THREAD

**Issue by Richardlyq** [DefTruth/RobustVideoMatting.lite.ai.toolkit#34]
作者大佬，您好，我已经成功编译了lite.tool.kit，lite.ai.toolkit\build\lite.ai.toolkit\bin\lite_rvm应该也能正常运行，然后用build/lite.ai.toolkit替换了RobustVideoMatting.lite.ai.toolkit/lite.ai.toolkit，也修改了CMakeLists,像在linux一样也配置了环境变量 export LD_LIBRARY_PATH=./lite.ai.toolkit/lib:$LD_LIBRARY_PATH。但是sh ./build.sh的时候还是报错？您能看看哪里错了嘛？
![image](https://user-images.githubusercontent.com/78252642/160282380-fd429a9d-f249-41a6-b939-c3b2c09c38e9.png)

**Comment by DefTruth** [comment]
windows下不需要export环境变量啊，那是在linux下才要的😂。另外就是windows下的opencv库名称也要改的，linux和mac都是会编译出很多个库，但是windows下opencv只有一个单体的库。windows下我没有试过，最优体验建议使用linux或mac，关于windows下的用法可以参考lite.ai.toolkit相关的issue

**Comment by Richardlyq** [comment]
![image](https://user-images.githubusercontent.com/78252642/160283004-e18fcb71-2cbc-4fb3-816a-a6232d976535.png)
我这里不知道怎么就乱码了，好像看网上的也没搞好，用另外一台机器跑，是报的这个错误

**Comment by DefTruth** [comment]
很抱歉，windows下我没有试过，最优体验建议使用linux或mac。

**Comment by Richardlyq** [comment]
> windows下不需要export环境变量啊，那是在linux下才要的😂。另外就是windows下的opencv库名称也要改的，linux和mac都是会编译出很多个库，但是windows下opencv只有一个单体的库。windows下我没有试过，最优体验建议使用linux或mac，关于windows下的用法可以参考lite.ai.toolkit相关的issue

对的，linux下跑的会有很多个库，windows下跑的只有几个库好像。linux下我已经跑成了，但是我还是想试试在windows下跑，~~

**Comment by Richardlyq** [comment]
太奇怪了，linux下和windows下基本上是一样的操作，但是前者跑的没毛病，后者就跑不了

**Comment by Richardlyq** [comment]
lite.ai.toolkit\build\lite.ai.toolkit\bin\lite_rvm，这个运行之后有什么结果呀？我怎么每次跑到700多的时候，快跑完了的时候，就自动给我退出来了呢

**Comment by DefTruth** [comment]
> 太奇怪了，linux下和windows下基本上是一样的操作，但是前者跑的没毛病，后者就跑不了

肯定啊，这两个就不是一样的操作系统啊，很多东西都不一样的啊

**Comment by DefTruth** [comment]
> lite.ai.toolkit\build\lite.ai.toolkit\bin\lite_rvm，这个运行之后有什么结果呀？我怎么每次跑到700多的时候，快跑完了的时候，就自动给我退出来了呢

有log就是正常的，你可以看一下源代码是怎么处理的
