### ISSUE TITLE
关于macos公证问题

### ISSUE THREAD

**Issue by synmans** [DefTruth/RobustVideoMatting.lite.ai.toolkit#41]
把lite.ai.toolkit的dylib库封装到app打包后，可以进行codesign并应用公证。
但是从非本地下载后，mac的Gatekeeper会提示无法通过认证。是苹果对某些库有限制吗？

**Comment by DefTruth** [comment]
这个不了解

**Comment by synmans** [comment]
验证了一下，只是复制到app中就会被检测到。应该是苹果对一些库进行了扫描
