### ISSUE TITLE
摄像头实时视频流推理时速度越来越慢且发现内存泄漏？

### ISSUE THREAD

**Issue by li-wenquan** [DefTruth/RobustVideoMatting.lite.ai.toolkit#43]
你好，请教一下，我用于摄像头实时视频流推理时，随着时间的推移时速度会变慢，虽然没有观察到内存有明显的增长，但当我使用Visual Leak Detector工具检测时发现内存有一处泄漏（如下所示），问题似乎出现在opencv？谢谢。
WARNING: Visual Leak Detector detected memory leaks!
---------- Block 48 at 0x000000002E664860: 256 bytes ----------
  Leak Hash: 0x3299BB0A, Count: 1, Total 256 bytes
  Call Stack (TID 3656):
    msvcrt.dll!malloc()
    (Module name unavailable)!Ordinal1040() + 0x5F bytes
    (Module name unavailable)!Ordinal1040() + 0x22C bytes
    (Module name unavailable)!Ordinal1040() + 0x3D5 bytes
    ntdll.dll!RtlActivateActivationContextUnsafeFast() + 0x11D bytes
    ntdll.dll!LdrGetProcedureAddressEx() + 0x2D7 bytes
    ntdll.dll!LdrGetProcedureAddressEx() + 0x6A bytes
    ntdll.dll!LdrGetProcedureAddressEx() + 0xF0 bytes
    ntdll.dll!RtlSwitchedVVI() + 0xD07 bytes
    ntdll.dll!RtlGetFullPathName_UstrEx() + 0x231E bytes
    ntdll.dll!RtlDosPathNameToNtPathName_U() + 0xD4 bytes
    ntdll.dll!LdrLoadDll() + 0xE4 bytes
    DtFrame64.dll!EATUninstallRaw() + 0x53B22 bytes
    KERNELBASE.dll!LoadLibraryExW() + 0x162 bytes
    TSafeDoc64.dll!0x00007FFFEF7D563C()
    TSafeDoc64.dll!0x00007FFFEF7CA0F3()
    winhadnt64.dll!InitUPDLShareMemory() + 0x41230 bytes
    DtFrame64.dll!EATUninstallRaw() + 0x3C129 bytes
    combase.dll!StringFromGUID2() + 0xB0DD bytes
    combase.dll!StringFromGUID2() + 0xB026 bytes
    combase.dll!StringFromGUID2() + 0xADF8 bytes
    combase.dll!StringFromGUID2() + 0xAA3A bytes
    combase.dll!CoCreateInstance() + 0x2C30 bytes
    combase.dll!Ordinal67() + 0xB5D bytes
    combase.dll!Ordinal67() + 0x4D6 bytes
    combase.dll!InternalCoIsSurrogateProcess() + 0x6DD0 bytes
    combase.dll!CoTaskMemRealloc() + 0x5E7C bytes
    combase.dll!CoDisableCallCancellation() + 0x128 bytes
    combase.dll!Ordinal167() + 0x500 bytes
    combase.dll!CoTaskMemRealloc() + 0x2A31 bytes
    combase.dll!CoDisableCallCancellation() + 0x4E0 bytes
 combase.dll!InternalCoIsSurrogateProcess() + 0x6DD0 bytes
    combase.dll!InternalCoIsSurrogateProcess() + 0x303F bytes
    combase.dll!InternalCoIsSurrogateProcess() + 0x6DD0 bytes
    combase.dll!CoCreateInstance() + 0x190A bytes
    combase.dll!CoCreateInstance() + 0x3BA bytes
    combase.dll!CoCreateInstance() + 0x10C bytes
    winhadnt64.dll!InitUPDLShareMemory() + 0x43458 bytes
    DtFrame64.dll!EATUninstallRaw() + 0x5E5FF bytes
    (Module name unavailable)!DllCanUnloadNow() + 0xE84D bytes
    (Module name unavailable)!DllCanUnloadNow() + 0xF2F0 bytes
    (Module name unavailable)!DllCanUnloadNow() + 0x1F66 bytes
    (Module name unavailable)!DllCanUnloadNow() + 0x125D bytes
    (Module name unavailable)!0x00007FFFB5BB3F5D()
    MFCORE.DLL!MFCreateDeviceSource() + 0x490 bytes
    (Module name unavailable)!DllUnregisterServer() + 0xDA8 bytes
    (Module name unavailable)!DllUnregisterServer() + 0x6C6 bytes
    (Module name unavailable)!0x00007FFFB91A39F8()
    (Module name unavailable)!DllUnregisterServer() + 0x21C2 bytes
    (Module name unavailable)!DllUnregisterServer() + 0x24BF bytes
    opencv_world455d.dll!cv::Matx_SubOp::operator=() + 0x3171E18 bytes
    opencv_world455d.dll!cv::Matx_SubOp::operator=() + 0x3178DF3 bytes
    opencv_world455d.dll!cv::Matx_SubOp::operator=() + 0x3178371 bytes
    opencv_world455d.dll!cv::Matx_SubOp::operator=() + 0x31784DB bytes
    opencv_world455d.dll!cv::Matx_SubOp::operator=() + 0x3174AFB bytes
    opencv_world455d.dll!cv::Matx_SubOp::operator=() + 0x316D722 bytes
    opencv_world455d.dll!cv::Matx_SubOp::operator=() + 0x316CAAD bytes
    opencv_world455d.dll!cv::Matx_SubOp::operator=() + 0x316D181 bytes
    opencv_world455d.dll!cv::Matx_SubOp::operator=() + 0x316D0A9 bytes
  Data:
    F0 11 EC 8A    FF 7F 00 00    E0 11 EC 8A    FF 7F 00 00     ........ ........
    30 12 EC 8A    FF 7F 00 00    90 12 EC 8A    FF 7F 00 00     0....... ........
    80 13 EC 8A    FF 7F 00 00    90 13 EC 8A    FF 7F 00 00     ........ ........
    F0 13 EC 8A    FF 7F 00 00    90 14 EC 8A    FF 7F 00 00     ........ ........
    B0 12 EC 8A    FF 7F 00 00    00 A7 EC 8A    FF 7F 00 00     ........ ........
    D0 12 EC 8A    FF 7F 00 00    40 14 EC 8A    FF 7F 00 00     ........ @.......
    60 14 EC 8A    FF 7F 00 00    B0 14 EC 8A    FF 7F 00 00     `....... ........
    D0 14 EC 8A    FF 7F 00 00    F0 14 EC 8A    FF 7F 00 00     ........ ........
    20 15 EC 8A    FF 7F 00 00    E0 15 EC 8A    FF 7F 00 00     ........ ........
    40 10 EC 8A    FF 7F 00 00    50 10 EC 8A    FF 7F 00 00     @....... P.......
    30 10 EC 8A    FF 7F 00 00    E0 A6 EC 8A    FF 7F 00 00     0....... ........
    C0 A6 EC 8A    FF 7F 00 00    F0 A6 EC 8A    FF 7F 00 00     ........ ........
    D0 A6 EC 8A    FF 7F 00 00    E0 64 EC 8A    FF 7F 00 00     ........ .d......
    B0 64 EC 8A    FF 7F 00 00    F0 12 EC 8A    FF 7F 00 00     .d...... ........
    A0 13 EC 8A    FF 7F 00 00    B0 13 EC 8A    FF 7F 00 00     ........ ........
    00 66 EC 8A    FF 7F 00 00    20 14 EC 8A    FF 7F 00 00     .f...... ........

**Comment by DefTruth** [comment]
我没有在windows跑过，你试一下换低版本的opencv试一下？比如4.5.2

**Comment by li-wenquan** [comment]
> 我没有在windows跑过，你试一下换低版本的opencv试一下？比如4.5.2

我试过4.5.2版本，但同样检测到内存泄漏，但当我使用3.4.16版本则没有检测到内存泄露，我不知道Visual Leak Detector工具是否足够精准，在没有更换opencv版本之前，有时也会检测不到内存泄漏，但大多数都检测到，4.5.2也类似，更换为3.4.16后我测试了七八次，都没有检测到泄露。但是，即便没有发现内存泄漏，当我使用GPU推理时，随着时间的推移速度也会下降，一开始很快，约0.65s左右，后面会有大幅下降的趋势，最后总体稳定在0.10左右（如下所示），这里所说的稳定是指在最后5分钟内基本稳定，但我还不清楚继续运行半小时甚至更久会发生什么。当我使用cpu在单线程模式下推理时我运行了约10分钟，没有观察到速度下降的趋势；当我使用cpu在多线程模式下推理时，总体上速度也有较小幅度的下降，这可能是正常的。
GPU每一帧推理的耗时情况（为了简洁，存在省略或截取）：
T=7.382T=0.066T=0.066T=0.065T=0.065T=0.064T=0.069T=0.067T=0.069T=0.065T=0.066T=0.065T=0.066T=0.066T=0.066T=0.066T=0.064T=0.066T=0.065T=0.063T=0.066T=0.066T=0.066T=0.067T=0.063T=0.066T=0.067T=0.065T=0.063T=0.066T=0.065T=0.065T=0.065T=0.066T=0.067T=0.066T=0.066T=0.065T=0.065T=0.065T=0.066T=0.067T=0.064T=0.065T=0.065T=0.065T=0.067T=0.072T=0.064T=0.065T=0.065T=0.068T=0.065T=0.064T=0.064T=0.063T=0.067T=0.066T=0.066T=0.065T=0.065T=0.065T=0.066T=0.066T=0.065T=0.066T=0.065T=0.066T=0.066T=0.066T=0.066T=0.081T=0.087T=0.095T=0.09T=0.09T=0.071T=0.072T=0.072T=0.076T=0.082T=0.082T=0.079T=0.079T=0.105T=0.098T=0.077T=0.078T=0.092T=0.078T=0.075T=0.077
......
T=0.073T=0.073T=0.075T=0.073T=0.074T=0.073T=0.074T=0.073T=0.074T=0.074T=0.072T=0.074T=0.074T=0.073T=0.074T=0.074T=0.072T=0.074T=0.072T=0.077T=0.074T=0.075T=0.073T=0.075T=0.073T=0.073T=0.074T=0.072T=0.074T=0.085T=0.101T=0.1T=0.099T=0.099T=0.099T=0.1T=0.099T=0.099T=0.103T=0.1T=0.099T=0.101T=0.101T=0.099T=0.1T=0.1T=0.1T=0.099T=0.1T=0.101T=0.1T=0.099T=0.099T=0.099T=0.1T=0.1T=0.1T=0.1T=0.099T=0.097T=0.099T=0.099T=0.101T=0.098T=0.099T=0.099T=0.098T=0.098T=0.1T=0.099T=0.1T=0.099T=0.1T=0.099T=0.098T=0.1T=0.099T=0.1T=0.1T=0.099T=0.103T=0.099T=0.099T=0.098T=0.098T=0.1T=0.101T=0.099T=0.099
......
T=0.101T=0.101T=0.101T=0.101T=0.1T=0.099T=0.1T=0.101T=0.101T=0.1T=0.098T=0.543T=0.547T=0.541T=0.54T=0.558T=0.564T=0.565T=0.565T=0.598T=0.634T=0.636T=0.63T=0.636T=0.635T=0.101T=0.101T=0.101T=0.1T=0.099T=0.1T=0.101T=0.101T=0.1T=0.098T=0.543T=0.547T=0.541T=0.54T=0.558T=0.564T=0.565T=0.565T=0.598T=0.634T=0.636T=0.63T=0.636T=0.635T=0.388T=0.118T=0.119T=0.118T=0.117T=0.103T=0.114T=0.116T=0.114T=0.118T=0.117T=0.118T=0.106T=0.113T=0.119T=0.118T=0.12T=0.119T=0.117T=0.104T=0.118T=0.115T=0.118T=0.12T=0.117T=0.118T=0.106T=0.116T=0.12T=0.118T=0.12T=0.118T=0.113T=0.1T=0.112T=0.117T=0.114T=0.118T=0.119T=0.13T=0.104T=0.115T=0.12T=0.12T=0.116T=0.109T=0.12T=0.119T=0.119T=0.118T=0.105T=0.111T=0.543T=0.543T=0.548T=0.54T=0.566T=0.576T=0.572T=0.567T=0.633T=0.637T=0.638T=0.633T=0.634T=0.613T=0.156T=0.098T=0.123T=0.126T=0.116T=0.12T=0.115T=0.12T=0.103T=0.117T=0.122T=0.12T=0.119T=0.118T=0.103T=0.117T=0.115T=0.12
......
最后五分钟的耗时（只粘贴了部分，基本稳定）：
T=0.101T=0.1T=0.099T=0.101T=0.1T=0.101T=0.103T=0.101T=0.101T=0.101T=0.101T=0.101T=0.101T=0.102T=0.1T=0.101T=0.101T=0.101T=0.101T=0.1T=0.105T=0.1T=0.102T=0.102T=0.101T=0.101T=0.102T=0.1T=0.102T=0.104T=0.1T=0.1T=0.1T
